// <auto-generated />
using System;
using Kursach_ind_4kurs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kursach_ind_4kurs.Migrations
{
    [DbContext(typeof(Bank_indv_zdContext))]
    [Migration("20231207190928_Show")]
    partial class Show
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kursach_ind_4kurs.Deal", b =>
                {
                    b.Property<int>("IdDeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDeal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealDiscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FioClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployeeNavigationIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("ValutaId")
                        .HasColumnType("int");

                    b.HasKey("IdDeal");

                    b.HasIndex("ClientId");

                    b.HasIndex("IdEmployeeNavigationIdEmployee");

                    b.HasIndex("ValutaId");

                    b.ToTable("Deal");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.DepositType", b =>
                {
                    b.Property<string>("DepositType1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionDeposit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinSumDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTermDeposit")
                        .HasColumnType("int");

                    b.Property<string>("NameDeposit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentDeposit")
                        .HasColumnType("float");

                    b.HasKey("DepositType1");

                    b.ToTable("DepositType");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Deposits", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeDepositType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeDepositTypeNavigationDepositType1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("DepositName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DepositPrecent")
                        .HasColumnType("float");

                    b.Property<int>("DepositTerm")
                        .HasColumnType("int");

                    b.Property<decimal?>("SumDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DepositId");

                    b.HasIndex("CodeDepositTypeNavigationDepositType1");

                    b.HasIndex("DealId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeEmployee")
                        .HasColumnType("int");

                    b.Property<string>("FioEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaryEmploee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelephoneEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Kurs", b =>
                {
                    b.Property<int>("IdValuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kurs1")
                        .HasColumnType("int");

                    b.Property<string>("ValutaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdValuta");

                    b.ToTable("Kurs");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Loans", b =>
                {
                    b.Property<int>("IdLoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDeal")
                        .HasColumnType("int");

                    b.Property<int?>("IdDealNavigationIdDeal")
                        .HasColumnType("int");

                    b.Property<int>("IdValuta")
                        .HasColumnType("int");

                    b.Property<double>("LoanPerecent")
                        .HasColumnType("float");

                    b.Property<DateTime>("LoanTerms")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLoan");

                    b.HasIndex("IdDealNavigationIdDeal");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FioClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneClient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Deal", b =>
                {
                    b.HasOne("Kursach_ind_4kurs.Models.Client", "Client")
                        .WithMany("Deal")
                        .HasForeignKey("ClientId");

                    b.HasOne("Kursach_ind_4kurs.Employee", "IdEmployeeNavigation")
                        .WithMany("Deal")
                        .HasForeignKey("IdEmployeeNavigationIdEmployee");

                    b.HasOne("Kursach_ind_4kurs.Kurs", "Valuta")
                        .WithMany("Deal")
                        .HasForeignKey("ValutaId");
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Deposits", b =>
                {
                    b.HasOne("Kursach_ind_4kurs.DepositType", "CodeDepositTypeNavigation")
                        .WithMany("Deposits")
                        .HasForeignKey("CodeDepositTypeNavigationDepositType1");

                    b.HasOne("Kursach_ind_4kurs.Deal", "Deal")
                        .WithMany("Deposits")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kursach_ind_4kurs.Loans", b =>
                {
                    b.HasOne("Kursach_ind_4kurs.Deal", "IdDealNavigation")
                        .WithMany("Loans")
                        .HasForeignKey("IdDealNavigationIdDeal");
                });
#pragma warning restore 612, 618
        }
    }
}
